spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/signmanager
    username: root
    password: Shkshk1212!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성 (none → validate → update → create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG        # Hibernate SQL 직접 로그
    org.hibernate.type: TRACE       # 쿼리 파라미터 로그
    com.signproject.signmanager.util.JwtTokenProvider: DEBUG

server:
  port: 8080


